# -*- coding: utf-8 -*-
"""run 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dwGgp_k9bf2aRfV7BDJbmx7teR42HA5A
"""

from cube_basics import *

cube = RubiksCube(n=3)
cube.shuffle(l_rot =5,u_rot =14)
print(cube.stringify())